# Generated by Django 4.1 on 2022-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
